languageCode = 'en-US'

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/'

  [[menus.main]]
    name = 'Work'
    pageRef = '/work'

  # [[menus.main]]
  #   name = 'Writing'
  #   pageRef = '/writing'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
